# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [1]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

import time
import numpy as np

array = np.arange(1,1000001)

lista = []
for i in range (1,1000001):
    lista.append(i)
    

def calculaarray(arg):
    inicio = time.time()
    calc = (lambda x: x * 2)          
    calc(arg)
    fim = time.time()
    print("Tempo de execução array: {}".format(fim - inicio))

def calculalista(arg):
    inicio = time.time()
    calc = (lambda x: x * 2)          
    calc(arg)
    fim = time.time()
    print("Tempo de execução list: {}".format(fim - inicio))
    
    
calculaarray(array)
calculalista(lista)

Tempo de execução array: 0.003999948501586914
Tempo de execução list: 0.07900452613830566


### Exercício 2

In [2]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

vetor = np.arange(1,11)
print(vetor)

vetor[5] = 0
vetor[8] = 0

print(vetor)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  0  7  8  0 10]


### Exercício 3

In [3]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(x[0])

[1 2 3]


### Exercício 4

In [4]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("\nTerceira linha:{}".format(y[2]))
print("Primeira linha: {}\nSegunda linha:{}".format(y[0],y[1]))
print("Primeira e segunda coluna:{}".format(y[:2, 1:]))



Terceira linha:[7 8 9]
Primeira linha: [1 2 3]
Segunda linha:[4 5 6]
Primeira e segunda coluna:[[2 3]
 [5 6]]


### Exercício 5

In [5]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
np.transpose(arr)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [6]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

res = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
res

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [7]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
from numpy import save 
from numpy import load

#Salvando arrayA em disco
arrayA = np.arange(1,11)
save('arrayA.npy', arrayA)

#Carregando valores para arrayB
arrayB = load('arrayA.npy')

arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercício 8

In [8]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd

obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

pd.unique(obj)

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [9]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
data = resp.json()

In [10]:
from pandas import DataFrame

df = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
df

number                                              title  \
0    37153  BUG: rolling.median/quantile does not work wit...   
1    37152  RecursionError when selecting single column fr...   
2    37151  API/BUG: empty sum with td64 NaT or timedelta(0)?   
3    37150                  BUG: indexing bugs #26490, #13691   
4    37149     BUG: GroupBy().fillna() performance regression   
5    37148             BUG: DataFrame[td64].sum(skipna=False)   
6    37145  BUG: Fix bug in quantile() for resample and gr...   
7    37144      BLD: update build requirement for py39 #37135   
8    37141  BUG: groupby.rolling.mean seems to roll over d...   
9    37140          BUG: algos.diff with datetimelike and NaT   
10   37139  BUG: Surprisingly large memory usage in groupb...   
11   37137  TYP: use overload to refine return type of res...   
12   37135             BUG:Installation problem in python 3.9   
13   37134          Remove the Label alias in pandas._typing.   
14   37132  BUG: raise when doing arithmetic on DataFrame ...   
15   37129  ENH: DataFrame.to_parquet() returns bytes if p...   
16   37128             TYP: add Shape alias to pandas._typing   
17   37127  ENH: Aggregation with multiple columns in one ...   
18   37126  [REDO] CLN: core/dtypes/cast.py::maybe_downcas...   
19   37125                 Add test_masking_duplicate_columns   
20   37124                     REF: IntervalArray comparisons   
21   37121  ENH: No need to call _choose_path in Dataframe...   
22   37119                                  typing_extensions   
23   37118  PERF: regression in DataFrame reduction ops pe...   
24   37117         CI: check for numpy.random-related imports   
25   37115  BUG: unstack on 'int' dtype prevent fillna to ...   
26   37110  BLD: extract GH Actions check function to avoi...   
27   37109  PERF: Faster comparisons of indexes when compa...   
28   37108  TYP: fix typing errors for mypy==0.790, bump m...   
29   37107         BUG: Fixes #36918 boxplots with matplotlib   

                                               labels state  
0   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
1   [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
4   [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
5   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
6   [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
7   [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
8   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
11  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
12  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
13  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
14  [{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...  open  
15  [{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODU...  open  
16  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
17  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
18  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
19  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
20  [{'id': 150096370, 'node_id': 'MDU6TGFiZWwxNTA...  open  
21                                                 []  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
24                                                 []  open  
25  [{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgx...  open  
26  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
27  [{'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMj...  open  
28  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
29                                                 []  open

### Exercício 10

In [16]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import random

conn = sqlite3.connect('bancoteste.db')
c = conn.cursor()
dados = [('José Ferreira Neto', 'Analytics', 40),
        ('Alice Sanches', 'Comercial', 20),
        ('Mauro Isaias', 'Analytics', 18),
        ('Fernanda Machado', 'Operações', 30),
        ('Maria Prado', 'Financeiro', 25)]

def createtable():
    c.execute("CREATE TABLE IF NOT EXISTS Funcionarios(nome TEXT, departamento TEXT, idade INTEGER)") 
    
def insertTable():
    c.executemany("INSERT INTO Funcionarios VALUES (?,?,?)", dados)
    conn.commit()

SQL_QUERY = "SELECT * FROM Funcionarios"

df = pd.read_sql_query(SQL_QUERY, conn)

df

nome departamento  idade
0   José Ferreira Neto    Analytics     40
1        Alice Sanches    Comercial     20
2         Mauro Isaias    Analytics     18
3     Fernanda Machado    Operações     30
4          Maria Prado   Financeiro     25
5   José Ferreira Neto    Analytics     40
6        Alice Sanches    Comercial     20
7         Mauro Isaias    Analytics     18
8     Fernanda Machado    Operações     30
9          Maria Prado   Financeiro     25
10  José Ferreira Neto    Analytics     40
11       Alice Sanches    Comercial     20
12        Mauro Isaias    Analytics     18
13    Fernanda Machado    Operações     30
14         Maria Prado   Financeiro     25

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>